language: node_js

sudo: enabled

node_js:
  - "8"

services:
- docker

before_install:
- curl -L https://github.com/docker/machine/releases/download/v0.13.0/docker-machine-`uname -s`-`uname -m` >/tmp/docker-machine && sudo install /tmp/docker-machine /usr/local/bin/docker-machine

script:
- docker-compose build


branches:
  only:
  - master
  after_success:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - aws s3 cp s3://guybelo-private/id_rsa . && chmod 0600 ./id_rsa
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker-compose push
  - docker-machine create -d generic --generic-ip-address=34.245.215.61 --generic-ssh-key ./id_rsa --generic-ssh-user ubuntu aws-docker
  - docker-machine env aws-docker
  - eval $(docker-machine env aws-docker)
  - docker-compose pull
  - docker-compose up -d
