language: node_js

sudo: enabled

node_js:
  - "8"

services:
- docker

script:
- docker-compose build

after_success:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- docker-compose push
- docker-machine create -d none -url=tcp://34.252.181.20:2376 aws-docker
- docker-machine env aws-docker
- docker-compose down
- docker-compose up -d
