language: node_js

sudo: enabled

node_js:
  - "8"

services:
- docker

before_install:
- curl -L https://github.com/docker/machine/releases/download/v0.13.0/docker-machine-`uname -s`-`uname -m` >/tmp/docker-machine && sudo install /tmp/docker-machine /usr/local/bin/docker-machine

script:
- docker-compose build

after_success:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- docker-compose push
- docker-machine create -d none -url=tcp://34.252.181.20:2376 aws-docker
- docker-machine regenerate-certs aws-docker -f
- docker-machine env aws-docker
- eval $(docker-machine env docker-compose-test)
- docker-compose down
- docker-compose up -d
