version: '3'
services:
  mysql:
    build: ./db_docker
    image: begenome/mysql:latest
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: "exit 0"
    ports:
      - "3306:3306"
  simple-web-app:
    build: .
    image: begenome/simple-web-app:latest
    depends_on:
      - "mysql"
    links:
      - mysql:mysql
    ports:
      - "3001:3001"