version: '2'
services:
  mysql:
    build: ./db_docker
    image: begenome/mysql:latest
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    mem_limit: '262144000'
  simple-web-app:
    build: .
    image: begenome/simple-web-app:latest
    depends_on:
      - "mysql"
    links:
      - mysql:mysql
    ports:
      - "3001:3001"
    mem_limit: '209715200'
    command: ["./wait-for-it.sh", "mysql:3306", "--", "node", "testapp1.js" ]
  nginx:
    build: ./proxy_docker
    image: begenome/nginx:latest
    depends_on:
      - simple-web-app
    ports:
      - "80:80"
    links:
      - simple-web-app:web
    mem_limit: '209715200'
