version: '2.1'
services:
  mysql:
    build: ./db_docker
    image: begenome/mysql:latest
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: "exit 0"
  simple-web-app:
    build: .
    image: begenome/simple-web-app:latest
    depends_on:
      mysql:
        condition: service_healthy
    links:
      - mysql:mysql
  nginx:
    build: ./proxy_docker
    depends_on:
    - simple-web-app
    ports:
    - "80:80"
    links:
      - simple-web-app:web
  